# Query to retrieve the RDF for the 268 terms of the LandVoc from Agrovoc

DESCRIBE
<http://aims.fao.org/aos/agrovoc/c_0543301f>
<http://aims.fao.org/aos/agrovoc/c_0b88a82c>
<http://aims.fao.org/aos/agrovoc/c_0cc6c485>
<http://aims.fao.org/aos/agrovoc/c_0d7ef890>
<http://aims.fao.org/aos/agrovoc/c_0e0e555b>
<http://aims.fao.org/aos/agrovoc/c_0eca1c57>
<http://aims.fao.org/aos/agrovoc/c_10222>
<http://aims.fao.org/aos/agrovoc/c_10391>
<http://aims.fao.org/aos/agrovoc/c_10967>
<http://aims.fao.org/aos/agrovoc/c_1177>
<http://aims.fao.org/aos/agrovoc/c_119678e7>
<http://aims.fao.org/aos/agrovoc/c_12069>
<http://aims.fao.org/aos/agrovoc/c_128d5eb6>
<http://aims.fao.org/aos/agrovoc/c_13609>
<http://aims.fao.org/aos/agrovoc/c_1374070277659>
<http://aims.fao.org/aos/agrovoc/c_1374155312641>
<http://aims.fao.org/aos/agrovoc/c_1374158672853>
<http://aims.fao.org/aos/agrovoc/c_1410424255662>
<http://aims.fao.org/aos/agrovoc/c_14569>
<http://aims.fao.org/aos/agrovoc/c_1464c114>
<http://aims.fao.org/aos/agrovoc/c_15590>
<http://aims.fao.org/aos/agrovoc/c_15686>
<http://aims.fao.org/aos/agrovoc/c_15992>
<http://aims.fao.org/aos/agrovoc/c_15d85712>
<http://aims.fao.org/aos/agrovoc/c_16062>
<http://aims.fao.org/aos/agrovoc/c_16112>
<http://aims.fao.org/aos/agrovoc/c_16141>
<http://aims.fao.org/aos/agrovoc/c_16532>
<http://aims.fao.org/aos/agrovoc/c_1662>
<http://aims.fao.org/aos/agrovoc/c_1666>
<http://aims.fao.org/aos/agrovoc/c_1782>
<http://aims.fao.org/aos/agrovoc/c_1783>
<http://aims.fao.org/aos/agrovoc/c_1791>
<http://aims.fao.org/aos/agrovoc/c_1798>
<http://aims.fao.org/aos/agrovoc/c_18389>
<http://aims.fao.org/aos/agrovoc/c_1839>
<http://aims.fao.org/aos/agrovoc/c_1882e93f>
<http://aims.fao.org/aos/agrovoc/c_195>
<http://aims.fao.org/aos/agrovoc/c_196>
<http://aims.fao.org/aos/agrovoc/c_1ada969a>
<http://aims.fao.org/aos/agrovoc/c_1d4ea7db>
<http://aims.fao.org/aos/agrovoc/c_1dfe5bfe>
<http://aims.fao.org/aos/agrovoc/c_203>
<http://aims.fao.org/aos/agrovoc/c_21323863>
<http://aims.fao.org/aos/agrovoc/c_2143>
<http://aims.fao.org/aos/agrovoc/c_2204>
<http://aims.fao.org/aos/agrovoc/c_2224>
<http://aims.fao.org/aos/agrovoc/c_22d01a32>
<http://aims.fao.org/aos/agrovoc/c_24403>
<http://aims.fao.org/aos/agrovoc/c_24843>
<http://aims.fao.org/aos/agrovoc/c_24866>
<http://aims.fao.org/aos/agrovoc/c_25195>
<http://aims.fao.org/aos/agrovoc/c_25243>
<http://aims.fao.org/aos/agrovoc/c_2593>
<http://aims.fao.org/aos/agrovoc/c_26e30c73>
<http://aims.fao.org/aos/agrovoc/c_2805>
<http://aims.fao.org/aos/agrovoc/c_2806>
<http://aims.fao.org/aos/agrovoc/c_28079>
<http://aims.fao.org/aos/agrovoc/c_2807>
<http://aims.fao.org/aos/agrovoc/c_2808>
<http://aims.fao.org/aos/agrovoc/c_28633>
<http://aims.fao.org/aos/agrovoc/c_28663>
<http://aims.fao.org/aos/agrovoc/c_28716>
<http://aims.fao.org/aos/agrovoc/c_28717>
<http://aims.fao.org/aos/agrovoc/c_28718>
<http://aims.fao.org/aos/agrovoc/c_28775>
<http://aims.fao.org/aos/agrovoc/c_28784>
<http://aims.fao.org/aos/agrovoc/c_28e0dafa>
<http://aims.fao.org/aos/agrovoc/c_28f78be5>
<http://aims.fao.org/aos/agrovoc/c_29157>
<http://aims.fao.org/aos/agrovoc/c_29225>
<http://aims.fao.org/aos/agrovoc/c_2934>
<http://aims.fao.org/aos/agrovoc/c_298db0d3>
<http://aims.fao.org/aos/agrovoc/c_2ee25bd9>
<http://aims.fao.org/aos/agrovoc/c_2f114c12>
<http://aims.fao.org/aos/agrovoc/c_3046>
<http://aims.fao.org/aos/agrovoc/c_3055>
<http://aims.fao.org/aos/agrovoc/c_3060>
<http://aims.fao.org/aos/agrovoc/c_31e765ad>
<http://aims.fao.org/aos/agrovoc/c_32620>
<http://aims.fao.org/aos/agrovoc/c_330588>
<http://aims.fao.org/aos/agrovoc/c_330633>
<http://aims.fao.org/aos/agrovoc/c_330634>
<http://aims.fao.org/aos/agrovoc/c_330886>
<http://aims.fao.org/aos/agrovoc/c_330982>
<http://aims.fao.org/aos/agrovoc/c_330990>
<http://aims.fao.org/aos/agrovoc/c_331049>
<http://aims.fao.org/aos/agrovoc/c_331524>
<http://aims.fao.org/aos/agrovoc/c_3369>
<http://aims.fao.org/aos/agrovoc/c_3389>
<http://aims.fao.org/aos/agrovoc/c_34823>
<http://aims.fao.org/aos/agrovoc/c_34ea1b1e>
<http://aims.fao.org/aos/agrovoc/c_34fdb55c>
<http://aims.fao.org/aos/agrovoc/c_35131>
<http://aims.fao.org/aos/agrovoc/c_35332>
<http://aims.fao.org/aos/agrovoc/c_357653f9>
<http://aims.fao.org/aos/agrovoc/c_36551>
<http://aims.fao.org/aos/agrovoc/c_36552>
<http://aims.fao.org/aos/agrovoc/c_36580>
<http://aims.fao.org/aos/agrovoc/c_36936>
<http://aims.fao.org/aos/agrovoc/c_37175>
<http://aims.fao.org/aos/agrovoc/c_37277>
<http://aims.fao.org/aos/agrovoc/c_37720>
<http://aims.fao.org/aos/agrovoc/c_37734>
<http://aims.fao.org/aos/agrovoc/c_37836>
<http://aims.fao.org/aos/agrovoc/c_37897>
<http://aims.fao.org/aos/agrovoc/c_37898>
<http://aims.fao.org/aos/agrovoc/c_37899>
<http://aims.fao.org/aos/agrovoc/c_37942>
<http://aims.fao.org/aos/agrovoc/c_37948>
<http://aims.fao.org/aos/agrovoc/c_37952>
<http://aims.fao.org/aos/agrovoc/c_3870>
<http://aims.fao.org/aos/agrovoc/c_3b50d6b6>
<http://aims.fao.org/aos/agrovoc/c_3ffda84e>
<http://aims.fao.org/aos/agrovoc/c_4172>
<http://aims.fao.org/aos/agrovoc/c_4173>
<http://aims.fao.org/aos/agrovoc/c_4174>
<http://aims.fao.org/aos/agrovoc/c_4175>
<http://aims.fao.org/aos/agrovoc/c_4178>
<http://aims.fao.org/aos/agrovoc/c_4180>
<http://aims.fao.org/aos/agrovoc/c_4181>
<http://aims.fao.org/aos/agrovoc/c_4182>
<http://aims.fao.org/aos/agrovoc/c_4184>
<http://aims.fao.org/aos/agrovoc/c_41b77c02>
<http://aims.fao.org/aos/agrovoc/c_4240>
<http://aims.fao.org/aos/agrovoc/c_434cfdd6>
<http://aims.fao.org/aos/agrovoc/c_45cd8441>
<http://aims.fao.org/aos/agrovoc/c_45ce1b52>
<http://aims.fao.org/aos/agrovoc/c_49983>
<http://aims.fao.org/aos/agrovoc/c_4bd6790a>
<http://aims.fao.org/aos/agrovoc/c_4d6b6100>
<http://aims.fao.org/aos/agrovoc/c_50226>
<http://aims.fao.org/aos/agrovoc/c_51a39a94>
<http://aims.fao.org/aos/agrovoc/c_550>
<http://aims.fao.org/aos/agrovoc/c_56c34d4d>
<http://aims.fao.org/aos/agrovoc/c_57156ff8>
<http://aims.fao.org/aos/agrovoc/c_573abb9f>
<http://aims.fao.org/aos/agrovoc/c_599d2e5c>
<http://aims.fao.org/aos/agrovoc/c_5d3b8015>
<http://aims.fao.org/aos/agrovoc/c_60fbd8f7>
<http://aims.fao.org/aos/agrovoc/c_6120d7bc>
<http://aims.fao.org/aos/agrovoc/c_6151>
<http://aims.fao.org/aos/agrovoc/c_6192>
<http://aims.fao.org/aos/agrovoc/c_62487b4a>
<http://aims.fao.org/aos/agrovoc/c_6350>
<http://aims.fao.org/aos/agrovoc/c_6448>
<http://aims.fao.org/aos/agrovoc/c_64d8574a>
<http://aims.fao.org/aos/agrovoc/c_6513>
<http://aims.fao.org/aos/agrovoc/c_653f04fe>
<http://aims.fao.org/aos/agrovoc/c_65c7772b>
<http://aims.fao.org/aos/agrovoc/c_6604>
<http://aims.fao.org/aos/agrovoc/c_666dbc26>
<http://aims.fao.org/aos/agrovoc/c_6699>
<http://aims.fao.org/aos/agrovoc/c_66afb052>
<http://aims.fao.org/aos/agrovoc/c_6701>
<http://aims.fao.org/aos/agrovoc/c_6704>
<http://aims.fao.org/aos/agrovoc/c_6705>
<http://aims.fao.org/aos/agrovoc/c_6887>
<http://aims.fao.org/aos/agrovoc/c_6b8a1f45>
<http://aims.fao.org/aos/agrovoc/c_6f79699c>
<http://aims.fao.org/aos/agrovoc/c_7017dc39>
<http://aims.fao.org/aos/agrovoc/c_70a14ab3>
<http://aims.fao.org/aos/agrovoc/c_7193>
<http://aims.fao.org/aos/agrovoc/c_72dd6860>
<http://aims.fao.org/aos/agrovoc/c_72efbdb8>
<http://aims.fao.org/aos/agrovoc/c_778a14cf>
<http://aims.fao.org/aos/agrovoc/c_781deefb>
<http://aims.fao.org/aos/agrovoc/c_7a25baee>
<http://aims.fao.org/aos/agrovoc/c_7bea427c>
<http://aims.fao.org/aos/agrovoc/c_7fc44e33>
<http://aims.fao.org/aos/agrovoc/c_7ffc9d69>
<http://aims.fao.org/aos/agrovoc/c_8085>
<http://aims.fao.org/aos/agrovoc/c_8086>
<http://aims.fao.org/aos/agrovoc/c_8088>
<http://aims.fao.org/aos/agrovoc/c_8320>
<http://aims.fao.org/aos/agrovoc/c_8420>
<http://aims.fao.org/aos/agrovoc/c_8491>
<http://aims.fao.org/aos/agrovoc/c_8532>
<http://aims.fao.org/aos/agrovoc/c_854e9e62>
<http://aims.fao.org/aos/agrovoc/c_85dfd05c>
<http://aims.fao.org/aos/agrovoc/c_862db225>
<http://aims.fao.org/aos/agrovoc/c_86524ff8>
<http://aims.fao.org/aos/agrovoc/c_8654e90e>
<http://aims.fao.org/aos/agrovoc/c_86cb818a>
<http://aims.fao.org/aos/agrovoc/c_88c1b116>
<http://aims.fao.org/aos/agrovoc/c_89d3dcbb>
<http://aims.fao.org/aos/agrovoc/c_8b624d6a>
<http://aims.fao.org/aos/agrovoc/c_8b6d895f>
<http://aims.fao.org/aos/agrovoc/c_8c59c597>
<http://aims.fao.org/aos/agrovoc/c_8c6882ab>
<http://aims.fao.org/aos/agrovoc/c_8dd43c79>
<http://aims.fao.org/aos/agrovoc/c_8e487587>
<http://aims.fao.org/aos/agrovoc/c_9000021>
<http://aims.fao.org/aos/agrovoc/c_9000022>
<http://aims.fao.org/aos/agrovoc/c_9000090>
<http://aims.fao.org/aos/agrovoc/c_9000091>
<http://aims.fao.org/aos/agrovoc/c_9000094>
<http://aims.fao.org/aos/agrovoc/c_9000096>
<http://aims.fao.org/aos/agrovoc/c_9000098>
<http://aims.fao.org/aos/agrovoc/c_9000100>
<http://aims.fao.org/aos/agrovoc/c_9000115>
<http://aims.fao.org/aos/agrovoc/c_9001019>
<http://aims.fao.org/aos/agrovoc/c_9024771d>
<http://aims.fao.org/aos/agrovoc/c_9044ce39>
<http://aims.fao.org/aos/agrovoc/c_92332>
<http://aims.fao.org/aos/agrovoc/c_931da360>
<http://aims.fao.org/aos/agrovoc/c_945c9e82>
<http://aims.fao.org/aos/agrovoc/c_958edb9d>
<http://aims.fao.org/aos/agrovoc/c_95fedfc9>
<http://aims.fao.org/aos/agrovoc/c_97241aeb>
<http://aims.fao.org/aos/agrovoc/c_9904d265>
<http://aims.fao.org/aos/agrovoc/c_9a4f48b4>
<http://aims.fao.org/aos/agrovoc/c_9c081fdc>
<http://aims.fao.org/aos/agrovoc/c_9c0e84b3>
<http://aims.fao.org/aos/agrovoc/c_9f542492>
<http://aims.fao.org/aos/agrovoc/c_a0982198>
<http://aims.fao.org/aos/agrovoc/c_a1b5abd0>
<http://aims.fao.org/aos/agrovoc/c_a245096c>
<http://aims.fao.org/aos/agrovoc/c_a291ae58>
<http://aims.fao.org/aos/agrovoc/c_a4f67d48>
<http://aims.fao.org/aos/agrovoc/c_a6fdfb0e>
<http://aims.fao.org/aos/agrovoc/c_a79c0bb8>
<http://aims.fao.org/aos/agrovoc/c_a9966ac9>
<http://aims.fao.org/aos/agrovoc/c_a9e7dd7f>
<http://aims.fao.org/aos/agrovoc/c_aa48855b>
<http://aims.fao.org/aos/agrovoc/c_aca7ac6d>
<http://aims.fao.org/aos/agrovoc/c_b317eba8>
<http://aims.fao.org/aos/agrovoc/c_b3372020>
<http://aims.fao.org/aos/agrovoc/c_b3864149>
<http://aims.fao.org/aos/agrovoc/c_b4d51db0>
<http://aims.fao.org/aos/agrovoc/c_b769471e>
<http://aims.fao.org/aos/agrovoc/c_b972e0ea>
<http://aims.fao.org/aos/agrovoc/c_ba3b2ea7>
<http://aims.fao.org/aos/agrovoc/c_bac66d94>
<http://aims.fao.org/aos/agrovoc/c_bb4738d4>
<http://aims.fao.org/aos/agrovoc/c_bdedf48c>
<http://aims.fao.org/aos/agrovoc/c_c0a7f4fb>
<http://aims.fao.org/aos/agrovoc/c_c10cdeb5>
<http://aims.fao.org/aos/agrovoc/c_c1543349>
<http://aims.fao.org/aos/agrovoc/c_c208d7f3>
<http://aims.fao.org/aos/agrovoc/c_c48aca78>
<http://aims.fao.org/aos/agrovoc/c_cbe171b4>
<http://aims.fao.org/aos/agrovoc/c_cc39a497>
<http://aims.fao.org/aos/agrovoc/c_cc3d0c47>
<http://aims.fao.org/aos/agrovoc/c_ccc27fe2>
<http://aims.fao.org/aos/agrovoc/c_cd44c0b3>
<http://aims.fao.org/aos/agrovoc/c_ceb73ce1>
<http://aims.fao.org/aos/agrovoc/c_d08b21b6>
<http://aims.fao.org/aos/agrovoc/c_d190bc52>
<http://aims.fao.org/aos/agrovoc/c_d42b49e7>
<http://aims.fao.org/aos/agrovoc/c_d774aa00>
<http://aims.fao.org/aos/agrovoc/c_da192f3f>
<http://aims.fao.org/aos/agrovoc/c_db4161cb>
<http://aims.fao.org/aos/agrovoc/c_dc5739ab>
<http://aims.fao.org/aos/agrovoc/c_de048871>
<http://aims.fao.org/aos/agrovoc/c_dec8141f>
<http://aims.fao.org/aos/agrovoc/c_dfbaecdf>
<http://aims.fao.org/aos/agrovoc/c_e236b2b1>
<http://aims.fao.org/aos/agrovoc/c_e5f9b786>
<http://aims.fao.org/aos/agrovoc/c_e6067b76>
<http://aims.fao.org/aos/agrovoc/c_ecf20c17>
<http://aims.fao.org/aos/agrovoc/c_ee93bbbe>
<http://aims.fao.org/aos/agrovoc/c_f73955fb>
<http://aims.fao.org/aos/agrovoc/c_f7cf8606>
<http://aims.fao.org/aos/agrovoc/c_f84a48c4>
<http://aims.fao.org/aos/agrovoc/c_f86e1a09>
<http://aims.fao.org/aos/agrovoc/c_ff890f6b>
<http://aims.fao.org/aos/agrovoc/c_ffd74ae5>