###############################
#### QUERYING AGROVOC #########
###############################

#SPARQL ENDPOINT: http://202.45.139.84:10035/catalogs/fao/repositories/agrovoc#query


# number of terms in Land Term Scheme

SELECT (COUNT (?concept) as ?c)
WHERE {
  ?concept a skos:Concept ;
           skos:inScheme <http://voc.landportal.info/landterms> .

} ORDER BY ?concept

##############################################
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>

SELECT ?lang (COUNT (?lang) as ?count)
WHERE {
  ?concept a skos:Concept ;
           skos:inScheme <http://voc.landportal.info/landterms> ;
           skosxl:prefLabel _:prefLabel .
  _:prefLabel skosxl:literalForm ?label .
  BIND (lang(?label) AS ?lang)
} 
GROUP BY ?lang
ORDER BY DESC(?count)

##############################################

PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>

SELECT ?lang (COUNT (?lang) as ?count)
WHERE {
  ?concept a skos:Concept ;
           skos:inScheme <http://voc.landportal.info/landterms> ;
           skosxl:altLabel _:altLabel .
  _:altLabel skosxl:literalForm ?label .
  BIND (lang(?label) AS ?lang)
} 
GROUP BY ?lang
ORDER BY DESC(?count)

##############################################

SELECT ?lang (COUNT (?lang) as ?count)
WHERE {
  ?concept a skos:Concept ;
  skos:inScheme <http://voc.landportal.info/landterms> ;
  skos:definition ?definition .
  ?definition rdf:value ?label
  BIND (lang(?label) AS ?lang)
} 
GROUP BY ?lang
ORDER BY DESC(?count)

##############################################
##############################################
##############################################

###############################
#### QUERYING LP SPARQL #######
###############################

SELECT ?lang (COUNT (?lang) as ?count)
FROM <http://landvoc.landportal.info>
WHERE {
  ?concept a skos:Concept ;
  skos:prefLabel ?label .
  BIND (lang(?label) AS ?lang)
} 
GROUP BY ?lang
ORDER BY DESC(?count)

##############################################

SELECT ?lang (COUNT (?lang) as ?count)
FROM <http://landvoc.landportal.info>
WHERE {
  ?concept a skos:Concept ;
  skos:altLabel ?label .
  BIND (lang(?label) AS ?lang)
} 
GROUP BY ?lang
ORDER BY DESC(?count)