# Query to retrieve the RDF for the 268 terms of the LandVoc from Agrovoc

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://aims.fao.org/aos/agrovoc/>

DESCRIBE ?concept
WHERE {
   ?concept rdf:type skos:Concept ;
            skos:inScheme <http://voc.landportal.info/landterms> .
    FILTER NOT EXISTS { ?concept owl:deprecated ?deprecated }
}
